name = "hugo-modus"
license = "MIT"
licenselink = "https://github.com/goofansu/hugo-modus/blob/main/LICENSE"
description = "An opinionated Hugo theme using the Modus themes colors."
homepage = "https://github.com/goofansu/hugo-modus"
demosite = "https://hugo-modus.yejun.dev/"

tags = ["blog", "dark", "light", "minimal", "tailwind"]
features = ["responsive", "card-style", "timeline-style", "syntax-highlighting"]

[author]
  name = "Yejun Su"
  homepage = "https://yejun.dev"
